/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as JurisdictionsRouteImport } from './routes/jurisdictions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const JurisdictionsRoute = JurisdictionsRouteImport.update({
  id: '/jurisdictions',
  path: '/jurisdictions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/dashboard': typeof DashboardRoute
  '/jurisdictions': typeof JurisdictionsRoute
  '/languages': typeof LanguagesRoute
  '/login': typeof LoginRoute
  '/roles': typeof RolesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/dashboard': typeof DashboardRoute
  '/jurisdictions': typeof JurisdictionsRoute
  '/languages': typeof LanguagesRoute
  '/login': typeof LoginRoute
  '/roles': typeof RolesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/dashboard': typeof DashboardRoute
  '/jurisdictions': typeof JurisdictionsRoute
  '/languages': typeof LanguagesRoute
  '/login': typeof LoginRoute
  '/roles': typeof RolesRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/dashboard'
    | '/jurisdictions'
    | '/languages'
    | '/login'
    | '/roles'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands'
    | '/dashboard'
    | '/jurisdictions'
    | '/languages'
    | '/login'
    | '/roles'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/dashboard'
    | '/jurisdictions'
    | '/languages'
    | '/login'
    | '/roles'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRoute
  DashboardRoute: typeof DashboardRoute
  JurisdictionsRoute: typeof JurisdictionsRoute
  LanguagesRoute: typeof LanguagesRoute
  LoginRoute: typeof LoginRoute
  RolesRoute: typeof RolesRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurisdictions': {
      id: '/jurisdictions'
      path: '/jurisdictions'
      fullPath: '/jurisdictions'
      preLoaderRoute: typeof JurisdictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRoute,
  DashboardRoute: DashboardRoute,
  JurisdictionsRoute: JurisdictionsRoute,
  LanguagesRoute: LanguagesRoute,
  LoginRoute: LoginRoute,
  RolesRoute: RolesRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
